### PR TITLE
Fix incomplete project properties

### LINKED ISSUE #12: Incomplete project properties
I found that in a certain case, I wasn't getting all of the preprocessor definitions that were present:

In a property sheet:

```xml
<ItemDefinitionGroup>
  <ClCompile>
     <PreprocessorDefinitions>NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
<ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In a project including the property sheet:

```xml
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In this case, I was missing `NOMINMAX`. I'm not sure why, but the functionality that was being used to get these values just left it out.

The tool wrappers can each cast their wrapped objects to an IVCRulePropertyStorage, which does return the correct information. It also handles property sheets and everything else, so it should simplify the code a lot.

I'll have a PR up shortly.

### PR DESCRIPTION
**Pull request by dakotahawkins**
I found that in a certain case, I wasn't getting all of the preprocessor
definitions that were present:

In a property sheet:

```xml
<ItemDefinitionGroup>
  <ClCompile>
     <PreprocessorDefinitions>NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
<ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In a project including the property sheet:

```xml
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In this case, I was missing `NOMINMAX`. I'm not sure why, but the
functionality that was being used to get these values just left it out.

The tool wrappers can each cast their wrapped objects to an
`IVCRulePropertyStorage`, which does return the correct information. It also
handles property sheets and everything else, so it should simplify the
code a lot.

Fixes #12

### CODE REVIEW

File: SourcetrailExtension/Utility/ProjectUtility.cs [hunk 1]
```diff
@@ -130,51 +130,20 @@ static public List<string> GetIncludeDirectories(IVCProjectWrapper project, IVCC
...
 			// source: http://www.mztools.com/articles/2014/MZ2014005.aspx
 
-			Logging.Logging.LogInfo("Attempting to retreive Include Directories for project '" + Logging.Obfuscation.NameObfuscator.GetObfuscatedName(project.GetName()) + "'");
+			Logging.Logging.LogInfo("Attempting to retrieve Include Directories for project '" + Logging.Obfuscation.NameObfuscator.GetObfuscatedName(project.GetName()) + "'");
 
 			List<string> includeDirectories = new List<string>();
 
 			if (vcProjectConfig != null && vcProjectConfig.isValid())
 			{
-				bool inspectPropertySheets = true;
```
Comment (dakotahawkins) [inline SourcetrailExtension/Utility/ProjectUtility.cs]: Special property sheet handling is no-longer necessary

File: SourcetrailExtensionTests/Helpers/TestPathResolver.cs [hunk 2]
```diff
@@ -28,9 +28,17 @@ public override string GetCompilationDatabaseFilePath()
...
 		{
-			if (path.Length > 0 && !path.StartsWith("<") && !System.IO.Path.IsPathRooted(path))
+			if (path.Length > 0 && !path.StartsWith("<"))
 			{
-				path = "<ProjectBaseDirectory>/" + path;
+				if (!System.IO.Path.IsPathRooted(path))
+				{
+					path = "<ProjectBaseDirectory>/" + path;
+				}
+				else if (path.StartsWith(project.GetProjectDirectory(), System.StringComparison.CurrentCultureIgnoreCase))
```
Comment (dakotahawkins) [inline SourcetrailExtensionTests/Helpers/TestPathResolver.cs]: To work around paths Visual Studio resolved for us, have the tests replace the real project dir with `<Macro $(ProjectDir)>`.

File: VCProjectEngineWrapper/VCCLCompilerToolWrapper.cs [hunk 3]
```diff
@@ -79,17 +81,17 @@ public string GetToolPath()
 
 		public string[] GetAdditionalIncludeDirectories()
 		{
-			return _wrapped.AdditionalIncludeDirectories.Split(';');
+			return _wrappedRules.GetEvaluatedPropertyValue("AdditionalIncludeDirectories").Split(';');
```
Comment (dakotahawkins) [inline VCProjectEngineWrapper/VCCLCompilerToolWrapper.cs]: Main change: access property values through `IVCRulePropertyStorage` wherever we can.

**Comment by mlangkabel** [comment]
Wow, great work at cutting down the clumsiness of the way we used to fetch include directories and preprocessor defines! 

Just one request before merging: In your commit you mentioned an example case that isn't working correctly in the current release of this extension. It would be great if you could add a test case for the situation you described so that we can make sure that this will never break again. Can you please do that?

**Comment by dakotahawkins** [comment]
Sure, I can add it to the existing property sheet case. It can pull in a configuration-specific definition and a generic one. I only wish I knew why the old version didn't work... maybe it just ignores `%(Additional...)` item metadata, the documentation doesn't say either way :(

**Comment by dakotahawkins** [comment]
You can review the test changes in isolation in [this commit.](https://github.com/dakotahawkins/vs-sourcetrail/commit/1f45181b6595e5e59b06ed86640ed28654c5958c)

File: SourcetrailExtensionTests/data/all_in_same_folder/test.vcxproj [hunk 4]
```diff
@@ -1,5 +1,5 @@
 ﻿<?xml version="1.0" encoding="utf-8"?>
-<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
Comment (dakotahawkins) [inline SourcetrailExtensionTests/data/all_in_same_folder/test.vcxproj]: Went ahead and let this upgrade. Annoying every time I cleaned my repo.

File: SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_property_sheet_usage.json [hunk 5]
```diff
@@ -1,12 +1,12 @@
...
     "file": "<ProjectBaseDirectory>/main.cpp"
   },
   {
     "directory": "<CompilationDatabaseFilePath>",
-    "command": "clang-tool -fms-extensions -fms-compatibility -fms-compatibility-version=19  -isystem \"<Macro $(ProjectDir)>custom_include_folder\"  -isystem \"<Macro $(VC_IncludePath)>\"  -isystem \"<Macro $(WindowsSDK_IncludePath)>\"  -D _DEBUG  -D _CONSOLE -std=c++14  \"<ProjectBaseDirectory>/main.cpp\"",
+    "command": "clang-tool -fms-extensions -fms-compatibility -fms-compatibility-version=19  -isystem \"<Macro $(ProjectDir)>custom_include_folder\"  -isystem \"<Macro $(VC_IncludePath)>\"  -isystem \"<Macro $(WindowsSDK_IncludePath)>\"  -D _DEBUG  -D _CONSOLE  -D CUSTOM_PREPROCESSOR_DEFINITION -std=c++14  \"<ProjectBaseDirectory>/main.cpp\"",
```
Comment (dakotahawkins) [inline SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_property_sheet_usage.json]: Include dir and preprocessor definitions:

1. From project

File: SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_noinherit_properties.vcxproj [hunk 6]
```diff
@@ -81,7 +81,7 @@
       <PrecompiledHeader>NotUsing</PrecompiledHeader>
       <WarningLevel>Level3</WarningLevel>
       <Optimization>Disabled</Optimization>
-      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE</PreprocessorDefinitions>
+      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE;CUSTOM_PREPROCESSOR_DEFINITION</PreprocessorDefinitions>
```
Comment (dakotahawkins) [inline SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_noinherit_properties.vcxproj]: Added this to mirror custom include

File: SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_property_sheet_usage.vcxproj [hunk 7]
```diff
@@ -80,7 +80,8 @@
       <PrecompiledHeader>NotUsing</PrecompiledHeader>
       <WarningLevel>Level3</WarningLevel>
       <Optimization>Disabled</Optimization>
-      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE;CUSTOM_PREPROCESSOR_DEFINITION;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <AdditionalIncludeDirectories>$(ProjectDir)custom_include_folder;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
```
Comment (dakotahawkins) [inline SourcetrailExtensionTests/data/project_with_property_sheet_usage/project_with_property_sheet_usage.vcxproj]: Added project-specific custom preprocessor definition and include

**Comment by mlangkabel** [comment]
Thanks for adding to the test case. I'll merge this now.
